stages:
  - build
  #- deploy


build-soc_config:
  stage: build
  image: git.module.ru:5050/nm6408_soft/docker_images/keymaker:1.0
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.module.ru/h3/linux-sdk/soc_config_tool
    - pip install rumboot-tools
    - make
  artifacts:
    paths:
    - soc_config_tool/output/

build-mt143-05:
  stage: build
  image: git.module.ru:5050/nm6408_soft/docker_images/keymaker:1.0
  scipt:
    - make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- mt143-05_defconfig
    - make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- all
    - rumboot-combine -a SD -i soc_config_tool/output/bivk.bin -i spl/u-boot-spl-dtb.rbi -i u-boot-dtb.img -o full_loader.bin
    artifacts:
    paths:
    - full_loader.bin
    expire_in: 4 week
